org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.95

mod_id=quest_giver
mod_name=Quest Giver
mod_license=MIT
mod_version=1.5.1
mod_group_id=com.saphienyako.quest_giver
mod_authors=SaphieNyako
mod_description=Quest Giver Mod.

